import Head from 'next/head'
// import { Button } from '../components/Button/Button'
// import { makeStyles } from '@material-ui/core/styles';
import Button from '@material-ui/core/Button';

export default function Home() {
  

  return (
    <div>
      <Head>
        <title>Oota Code Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <main >


      <Button variant="contained">Defaults</Button>
      <Button variant="contained" color="primary">
        Primary
      </Button>
      <Button variant="contained" color="secondary">
        Secondary
      </Button>
      <Button variant="contained" disabled>
        Disabled
      </Button>
      <Button variant="contained" color="primary" href="#contained-buttons">
        Link
      </Button>
      </main>

    </div>
  )
}
